token = ""
owners = [
    141231597155385344,
]
pubkey = ""
dm_uncaught_errors = true
user_agent = "MarriageBot (email@example.com)"
support_guild_id = 0
bot_support_role_id = 0
ephemeral_error_messages = true
owners_ignore_check_failures = true
cached_messages = 0

# MarriageBot-specific config items
max_family_members = 750  # The maximum amount of people you can have in a family
tree_file_location = "/var/www/images"  # The location where the tree files are to be output
is_server_specific = false

# Event webhook information - some of the events (noted) will be sent to the specified url
[event_webhook]
    event_webhook_url = ""
    [event_webhook.events]
        guild_join = false
        guild_remove = false
        shard_connect = false
        shard_disconnect = false
        shard_ready = false
        bot_ready = false
        unhandled_error = false

# The intents that the bot should start with
[intents]
    guilds = false
    members = false
    bans = false
    emojis = false
    integrations = false
    webhooks = false
    invites = false
    voice_states = false
    presences = false
    guild_messages = false
    dm_messages = false
    guild_reactions = false
    dm_reactions = false
    guild_typing = false
    dm_typing = false

# Data used to send API requests to whatever service
[bot_listing_api_keys]
    topgg_token = ""
    discordbotlist_token = ""

# Add our API keys
[api_keys]
    weebsh = ""

[bot_info]
    enabled = true
    include_stats = true
    content = """
        **MarriageBot** is a bot that lets you marry your friends, and adopt your enemies. Using commands like `adopt`, `makeparent`, and `marry`, you're able to create your own in-Discord family tree, which you can then check out with the `/tree` command!
    """
    thumbnail = ""
    image = "https://marriagebot.xyz/static/images/tree.png"
    links.Website = {url = "https://marriagebot.xyz"}
    links."Support Server" = {url = "https://discord.gg/vfl"}
    links.Github = {url = "https://github.com/Voxel-Fox-Ltd/MarriageBot"}
    links."Donate (Upgrade.Chat)" = {url = "https://upgrade.chat/checkout/208895639164026880"}
    links.Vote = {url = "https://top.gg/bot/marriagebot/vote"}

# Used to generate the invite link
[oauth]
    enabled = true
    client_id = "468281173072805889"
    scope = "bot applications.commands"
    permissions = [
        "send_messages",
        "attach_files",
        "embed_links",
        "add_reactions",
        "external_emojis",
    ]
    response_type = ""
    redirect_uri = ""

# This data is passed directly over to asyncpg.connect()
[database]
    enabled = true
    type = "postgres"
    user = "marriagebot"
    password = ""
    database = "marriagebot"
    host = "127.0.0.1"
    port = 5432

# This data is passed directly over to aioredis.connect()
[redis]
    enabled = true
    host = "127.0.0.1"
    port = 6379
    db = 0

[shard_manager]
    enabled = false
    host = "127.0.0.1"
    port = 8888

# The data that gets shoves into custom context for the embed
[embed]
    enabled = true  # whether or not to embed messages by default
    content = ""  # default content to be added to the embed message
    colour = 0  # a specific colour for the embed - 0 means random
    footer = [
        {text = "Learn how to get more children (/donate)", amount = 3},
        {text = "Join the official Discord server (/info)", amount = 3},
        {text = "Learn more about MarriageBot Gold (/gold)", amount = 3},
        {text = "Donate to keep MarriageBot alive (/donate)", amount = 10},
    ]

# What the bot is playing
[presence]
    activity_type = "watching"
    text = "you build families"
    status = "online"
    include_shard_id = false
    [presence.streaming]
        twitch_usernames = [
            "VoxelFoxKae",
        ]
        twitch_client_id = ""  # Your client ID - https://dev.twitch.tv/console/apps
        twitch_client_secret = ""  # Your client secret

# UpgradeChat API key data - https://upgrade.chat/developers
[upgrade_chat]
    client_id = ""
    client_secret = ""

# Statsd analytics port using the aiodogstatsd package
[statsd]
    host = "127.0.0.1"
    port = 8125  # This is the DataDog default, 9125 is the general statsd default
    constant_tags.service = "marriagebot"  # Put your bot name here - leave blank to disable stats collection
